"""add user_email to query

Revision ID: 42b41e26953e
Revises: 10d65b0bd798
Create Date: 2026-01-07 18:40:29.776733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b41e26953e'
down_revision: Union[str, None] = '10d65b0bd798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('user_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'user_email')
    # ### end Alembic commands ###
